### ISSUE TITLE
Hitting the API Rate Limit for the Star History

### ISSUE THREAD

**Issue by nathan-nicholson** [konstructio/kubefirst-api#517]
## Summary

When trying to visit the Starlet page in the [kubefirst README.md](https://github.com/konstructio/kubefirst?tab=readme-ov-file) to look at the history, we get hit with a page saying our GitHub API token limit is being exceeded (screenshot attached). 

<img src="https://uploads.linear.app/69be4292-0900-4250-b336-6a531b1e3741/eba08c59-1fb1-4f9a-98e1-0879423464ae/098c6d3a-c87f-4378-bd20-b8d11f48965b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY5YmU0MjkyLTA5MDAtNDI1MC1iMzM2LTZhNTMxYjFlMzc0MS9lYmEwOGM1OS0xZmIxLTRmOWEtOThlMS0wODc5NDIzNDY0YWUvMDk4YzZkM2EtYzg3Zi00Mzc4LWJkMjAtYjhkMTFmNDg5NjViIiwiaWF0IjoxNzM0MDE4Mzk0LCJleHAiOjMzMzA0NTc4Mzk0fQ.5bvdSCY8Atdr4-iJzioPqp9HzSLNJurmfzzJ_YojQFA " alt="image.png" width="700" data-linear-height="396" />

We should update whatever API token we're using so that we're not hitting this limit. Possibly create a bot user dedicated for this.

**Comment by fharper** [comment]
It's not our tool. It's your IP being rationed. Everyone can add their token if they reached the limit. It's not something we can control. As an example, I have no issue when I click on it since I usually use an token anytime I hit the APi for anything else, so not rationed for now.
